### ISSUE TITLE
安装环境报错

### ISSUE THREAD

**Issue by NikoHsu** [WindyLab/Gym-PPS#1]
您好，当我运行python setup.py install   的时候，显示
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from gym.version import VERSION
  File "D:\Gym-PPS-main\gym\__init__.py", line 17, in <module>
    from gym.spaces import Space
  File "D:\Gym-PPS-main\gym\spaces\__init__.py", line 1, in <module>
    from gym.spaces.space import Space
  File "D:\Gym-PPS-main\gym\spaces\space.py", line 1, in <module>
    from gym.utils import seeding
  File "D:\Gym-PPS-main\gym\utils\__init__.py", line 10, in <module>
    from .lib import *
ModuleNotFoundError: No module named 'gym.utils.lib'
提示缺少 'gym.utils.lib'，但是环境下已经安装了gym库
是否可以提供gym版本？requirement文档里没有找到

**Comment by XIAOYIXIA8888** [comment]
错误加一ModuleNotFoundError: No module named 'gym.utils.lib'

**Comment by pi-works** [comment]
Thank you for being interested in this research. I apologize for the delayed response, as I have recently graduated and left for a new research institute. After reviewing your query, we were unable to reproduce the error you encountered. To assist you in resolving the issue, I suggest the following steps:

1. **Avoid installing the official Gym package.** Instead, please use the custom package provided. If you have already installed the Gym package, I recommend completely removing the existing build, which is typically located in the following directory:
   `/home/your-name/.local/lib/python3.8/site-packages/gym-0.19.0-py3.8.egg`.
   Afterward, reinstall the custom package.
2. **Ensure that you are using Python 3.8 for this project.** I also recommend setting up a Python virtual environment to avoid potential version conflicts.
3. **If you encounter the error `NameError: name 'glPushMatrix' is not defined`** and the screen displays only a white background before quickly crashing, this issue is likely due to an incompatible version of pyglet. To resolve this, please downgrade pyglet to version 1.5.27 by running:
   `pip install pyglet==1.5.27`.
4. **If you see the error `'extras_require' must be a dictionary whose values are strings or lists,`** please run the following command in the terminal to update pip and setuptools:
   `pip install setuptools==57.5.0`.
5. **For Anaconda users, if you encounter the error `libGL error: MESA-LOADER: failed to open xxxxxx,`** open the `./bashrc` file in Anaconda and add the following line at the beginning:
   `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6`.

If you encounter any further issues, please feel free to contact me directly via the email address provided in the paper.

Additionally, we have identified a nice reproduction of our work. You can refer to the following GitHub repository:
https://github.com/xxnnnnn/PredatorPrey_RL_Reproduction.

I hope this information proves helpful. Thank you once again for your interest.

**Comment by pengpoom** [comment]
ModuleNotFoundError: No module named 'gym.utils.lib'
这个问题是在windows下才出现的，ubuntu下能正常运行

> 错误加一ModuleNotFoundError: No module named 'gym.utils.lib'
